# Generated by Django 5.2.4 on 2025-07-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campsites", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campsiteimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="campsiteimage",
            name="cloudflare_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
