# Generated by Django 5.2.4 on 2025-07-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campsites", "0002_remove_campsiteimage_image_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campsiteimage",
            options={"ordering": ["order"]},
        ),
    ]
