# Generated by Django 5.2.4 on 2025-07-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campsites", "0004_campsite_thumbnail_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campsite",
            name="thumbnail_image",
        ),
    ]
