# Generated by Django 5.2.4 on 2025-07-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campsites", "0005_remove_campsite_thumbnail_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campsite",
            options={"ordering": ["-created_at"]},
        ),
    ]
