# Generated by Django 5.2.4 on 2025-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campsites", "0006_alter_campsite_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campsite",
            name="blog_url",
        ),
        migrations.RemoveField(
            model_name="campsite",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="campsite",
            name="check_in",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campsite",
            name="check_out",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campsite",
            name="contact_number",
            field=models.CharField(blank=True, help_text="대표 번호", max_length=20),
        ),
        migrations.AddField(
            model_name="campsite",
            name="price",
            field=models.PositiveIntegerField(
                default=1, help_text="총 숙박 요금 (단위: 원)"
            ),
            preserve_default=False,
        ),
    ]
